### ISSUE TITLE
use mmp with vue component

### ISSUE THREAD

**Issue by thephucit** [Mindmapp/mmp#14]
How to user MMP Mindmapp inside vue component.
Thank!

**Comment by cedoor** [comment]
Hi @thephucit, sorry but I don't know in depth Vue.

**Comment by NikhilNamal17** [comment]
Hey, @cedoor can you help me out integrating mmp with React Component?

**Comment by cedoor** [comment]
Hi @NikhilNamal17, same thing, I don't know React in depth.
